# Generated by Django 2.1.1 on 2018-09-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_snippet_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
